version: 2
jobs:
  build:
    docker:
      - image: centos:7

    steps:
      - checkout

      - run:
          name: Install and configure mock 
          command: yum -y install epel-release && yum -y install mock && cp varnish-modules-backport/config/mock/epel-7-x86_64_varnish /etc/mock/. 

      - run:
          name: Print the Current Working Dir 
          command: find .
