version: 2
jobs:
  build:
    docker:
      - image: centos:7

    steps:
      - checkout

      - run:
          name: Install and configure mock 
          command: yum -y install epel-release && yum -y install mock rpm-build && cp ./config/mock/epel-7-x86_64_varnish.cfg /etc/mock

      - run:
          name: Mock Build
          command: /bin/mock -r epel-7-x86_64_varnish srpm/*.rpm

      - store_artifacts:
          path: /var/lib/mock/epel-7-x86_64_varnish/result/build.log

      - store_artifacts:
          path: /var/lib/mock/epel-7-x86_64_varnish/result/root.log
