version: 2
jobs:
  build:
    docker:
      - image: centos:7

    steps:
      - checkout

      - run:
          name: Install and configure mock 
          command: yum -y install epel-release && yum -y install mock rpm-build && cp ./config/mock/epel-7-x86_64_varnish.cfg /etc/mock

      - run:
          name: Print the Current Working Dir 
          command: find . && find /root
